// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GithubDarkPurple
{
    internal sealed partial class Vsix
    {
        public const string Id = "687d8010-bd44-4aad-9e83-fd3fb354c425";
        public const string Name = "Github Dark Purple Theme";
        public const string Description = @"A port of the 'Github Purple' VS Code theme by 4a454646 (based on the official Github Dark theme, but with purple accents!)";
        public const string Language = "en-US";
        public const string Version = "0.3";
        public const string Author = "Yann Duran";
        public const string Tags = "github, dark, purple, theme, yannduran, yd, luminous";
    }
}
