# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Build and Publish VSIX"

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master, develop]

env:
  VsixName: ${{ github.event.repository.name }}.vsix

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    env:
      Configuration: Release
      DeployExtension: False
      VsixManifestPath: src\source.extension.vsixmanifest
      VsixManifestSourcePath: src\source.extension.cs
    outputs:
      version: ${{ steps.vsix_version.outputs.version-number }}
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1
      with:
        nuget: 'false'
        sdk: 'false'
        msbuild: 'true'
        vs-test: 'false'

    - name: Increment VSIX version
      id: vsix_version
      uses: timheuer/vsix-version-stamp@v1
      with:
        version-type: revision
        manifest-file: ${{ env.VsixManifestPath }}
        vsix-token-source-file: ${{ env.VsixManifestSourcePath }}

    - name: Build Solution
      run: msbuild /v:m -restore /p:OutDir=\_built
      
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.VsixName }}
        path: /_built/**/*.vsix

  vsix-gallery:
    name: VSIX Gallery
    if: github.ref != 'refs/heads/master'
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download VSIX artifact
      uses: actions/download-artifact@v2 
      with:
        name: ${{ env.VsixName }}
    
    - name: Upload to VSIX Gallery
      uses: timheuer/openvsixpublish@v1
      with:
        vsix-file: ${{ env.VsixName }}

  vs-marketplace:
    name: VS Marketplace
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download VSIX artifact
      uses: actions/download-artifact@v2 
      with:
        name: ${{ env.VsixName }}
    
    - name: Publish extension to Marketplace
      if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]')
      uses: cezarypiatek/VsixPublisherAction@0.1
      with:
        extension-file: ${{ env.VsixName }}
        publish-manifest-file: 'vs-publish.json'
        personal-access-code: ${{ secrets.VS_MARKETPLACE_PAT }}
    
  github-release:
    name: Tag and Release
    if: github.ref == 'refs/heads/master'
    needs: [build, vs-marketplace]
    runs-on: windows-latest

    #env:
      #Version: ${{ needs.build.outputs.version }}
      #ReleaseTag: v${{ Version }}
      #ReleaseBody: Release ${{ Version }}

    steps:
    - name: Create GitHub Release
      if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]')
      uses: softprops/action-gh-release@v0.1.13
      with:
        tag_name: v${{ needs.build.outputs.version }}
        body: Release ${{ needs.build.outputs.version }}
        files: |
          **/*.vsix
