# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Build and Publish VSIX"

on:
  push:
    branches: [master, develop]
  #pull_request:
  #  branches: [master]
  workflow_dispatch:
    branches: master

env:
  RepoName: ${{ github.event.repository.name }}
  #IsMasterBranch: ${{ github.ref == 'refs/heads/master' }}
  #WorkflowDispatched: ${{ github.event_name == 'workflow_dispatch' }}
  # IsRelease: ${{ contains(github.event.head_commit.message, '[release]') }}

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    env:
      Configuration: Release
      DeployExtension: False
    outputs:
      VsixVersion: ${{ steps.increment_version.outputs.version-number }}
      VsixFullName: ${{ env.RepoName }}_v${{ steps.increment_vsix_version.outputs.version-number }}.vsix
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1
      with:
        nuget: 'false'
        sdk: 'false'
        msbuild: 'true'
        vs-test: 'false'

    - name: Increment VSIX version
      id: increment_vsix_version
      uses: timheuer/vsix-version-stamp@v1
      with:
        version-type: revision
        manifest-file: src\source.extension.vsixmanifest
        vsix-token-source-file: src\source.extension.cs

    - name: Print new VSIX version
      run: echo "New version is '${{ steps.increment_version.outputs.version-number }}'"

    - name: Build Solution
      run: msbuild /v:m -restore /p:OutDir=\_built # Configuration: Release, DeployExtension: False

    - name: Print _built file structure
      run: ls -l _built/
    
  upload-artifact:
    name: Upload VSIX artifact
    needs: build
    runs-on: windows-latest

    steps:
    - name: Upload VSIX
      uses: actions/upload-artifact@v2
      with:
        name: vsix-artifact
        path: /_built/**/${{ needs.build.outputs.VsixFullName }}
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

  vsix-gallery:
    name: VSIX Gallery
    if:   github.ref != 'refs/heads/master'
    needs: [build, upload-artifact]
    runs-on: windows-latest
    env:
      VsixFullName: ${{ needs.build.outputs.VsixFullName }}

    steps:
    - name: Download VSIX artifact
      uses: actions/download-artifact@v2 
      with:
        name: vsix-artifact
    
    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload to VSIX Gallery
      uses: timheuer/openvsixpublish@v1
      with:
        vsix-file: ${{ env.VsixFullName }}

  vs-marketplace:
    name: VS Marketplace
    if: github.ref == 'refs/heads/master'
    needs: [build, upload-artifact]
    runs-on: windows-latest
    env:
      VsixFullName: ${{ needs.build.outputs.VsixFullName }}

    steps:
    - name: Download VSIX artifact
      uses: actions/download-artifact@v2 
      with:
        name: ${{ env.VsixFullName }}
    
    - name: Publish extension to Marketplace
      uses: cezarypiatek/VsixPublisherAction@0.1
      with:
        extension-file: ${{ env.VsixFullName }}
        publish-manifest-file: src\publish-manifest.json
        personal-access-code: ${{ secrets.VS_MARKETPLACE_PAT }}
    
  github-release:
    name: Tag and Release
    if: github.ref == 'refs/heads/master'
    needs: [build, vs-marketplace]
    runs-on: windows-latest
    env:
      VsixVersion: ${{ needs.build.outputs.VsixVersion }}
      VsixFullName: ${{ needs.build.outputs.VsixFullName }}

    steps:
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        tag_name: v${{ env.VsixVersion }}
        body: Release ${{ env.VsixVersion }}
        files: ${{ env.VsixFullName }}
